### ISSUE TITLE
json2po fails on input json with numbers

### ISSUE THREAD

**Issue by racetiger** [translate/translate#3363]
json2po 1.14.0-alpha1 (also seen with 1.13)

I have 2 test json files 

test1.json  
```javascript
{ "text": "A simple string", "number": "42" }
```

test2.json  
```javascript
{ "text": "A simple string", "number": 42 }
```

I can successfully run :  json2po -P test1.json
```
processing 1 files...
#. extracted from test1.json
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2015-10-28 19:02+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: Translate Toolkit 1.14.0-alpha1\n"

#: .text
msgid "A simple string"
msgstr ""

#: .number
msgid "42"
msgstr ""
[###########################################] 100%
```

But test 2 fails : json2po -P test2.json
```
processing 1 files...
json2po: WARNING: Error processing: input test2.json, output None, template None: We don't handle these values:
Type: <type 'int'>
Data: 42
Previous: .number
[###########################################] 100%
```

I would not expect such failure, as test2.json was copied from test "test_filter" in [test_json2po.py](https://github.com/translate/translate/blob/master/translate/convert/test_json2po.py#L32)

It basically ruins the purpose of this converter for any json using number data types.

**Comment by claudep** [comment]
Just to be clear, would you expect the number being extracted or just ignored?

**Comment by racetiger** [comment]
just ignored would be fine, as defined in test_filter.

**Comment by Frexuz** [comment]
Same issue here. Rails uses these values in their default translation files (yml)

```
---
en-GB:
  number:
    currency:
      format:
        delimiter: ","
        format: "%u%n"
        precision: 2
        separator: "."
        significant: false
        strip_insignificant_zeros: false
        unit: "£"
```

How can we go around this?
